### ISSUE TITLE
Spotify Authorization seems to not work

### ISSUE THREAD

**Issue by wilkesalex** [larkinds/Spotify.MLH#43]
Hi guys

I'm from Pod 2.1.1 and I was checking out other explorer projects in retro week.

You project sounds really cool, I tried to give it a go! I found the following issues which led to the app not being authorized by spotify:

- There wasn't an example secrets file to use, but I guessed how to make it. I made a pull request if you want to add the example file you mentioned back in (assuming my one is OK). Here is my PR: https://github.com/larkinds/Spotify.MLH/pull/42
- Even so, it seems the client_id isn't passed to Spotify
- I hacked the redirectURI to include the client_id, but then when Spotify authoirzes the app, this error happens:
`Error exchanging authorization code for access token: An authentication error occurred while communicating with Spotify's Web API. Details: invalid_client.`

It's just my notes and I'm going through the retro week tasks, so no worries really, I think it's a nice project and you should submit it to the VS Code Extensions, once newbs like me can get it working easy!

**Comment by jkmartindale** [comment]
Ah, found the issue. Your template file doesn't export its variables, so if you open `extension.ts` you'll probably see something like this:  
![image](https://user-images.githubusercontent.com/11380394/114972088-66d27c80-9e43-11eb-9971-502eee16d036.png)

This import issue leads to `client_id` becoming undefined, which is why it's not sent in the web requests. Using the proper template should resolve the error.

Thanks for filing this issue, I added the proper secrets template to the repository.

**Comment by wilkesalex** [comment]
Hey @jkmartindale thanks for checking it out! I see , I learnt something with the "exports" thing then :) Thanks a lot!
